### ISSUE TITLE
Is there any way to validate custom domain email?

### ISSUE THREAD

**Issue by mhmdAljefri** [K-and-R/email_validator#55]
I have a scenario to validate if email exist on company domain. for example any email end with *@gmail.com*

**Comment by karlwilbur** [comment]
I like this idea. I'll add it to [my fork](https://github.com/karlwilbur/email_validator) and submit a PR. 

Do you think something like this:
```ruby
validates :my_email_attribute, email: {domain: 'example.com'}
# or, for `strict_mode`
validates :my_email_attribute, email: {domain: 'example.com', strict_mode: true}
```

**Comment by mhmdAljefri** [comment]
Sure it's

**Comment by karlwilbur** [comment]
As of `2.1.0`, we not have a `domain` option which takes a domain that will be used to further limit the validation.

Example:
```ruby
validates :email, email: {domain: 'gmail.com'}
```

See the `README` for more details.

I am closing this issue.
