### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by knagode** [K-and-R/email_validator#63]
After we upgraded to Rails 6, we noticed that email validation stopped working silently for email input like: `base@example` :(

**Comment by jpwynn** [comment]
yes, downgrade is the answer, unfortunately "abc@example.co,"  (with a comma) is not a valid email, yet passes under 2.0 (fails under 1.6.0). 

I'm grateful it got as far as 1.6.0 before the algorithm was watered-down.

I disagree with the notion that a validator should give a green light to greviously incorrect emails, for which there is zero possibility the user would successfully receive the confirmaiton email suggested: a) it makes the app look stupid, and b) the rather academic position posed as the reason to go loose ignores the hassle/confusion/delay that occurs when the confirmation email fails to show up? What __really__ happens in the real world is: John Doe who typed "johndoe@example" waits, doesn't see the email, waits some more, checks his spam folder, waits a little more, checks his spam folder again, then assumes if the website is broken, and gives up. (If you're lucky he writes in to complain.)

**Comment by karlwilbur** [comment]
@jpwynn, I agree. I am working on a new versions that validates based on RFC compliance. 

https://github.com/karlwilbur/email_validator

I expect to me merging that into a new release here within the next few months.

**Comment by karlwilbur** [comment]
While this loose validation is still the default, as of release `2.1.0` we now have the ability to easily obtain the validation you desire by using `mode: :moderate`. More detailed are in the `README`.

I am closing this issue.
