### ISSUE TITLE
Error when putting code in model

### ISSUE THREAD

**Issue by amenthe** [K-and-R/email_validator#64]
I kept getting this error undefined method my_email_attribute' for #User:0x00007fd032841908` could anyone help

**Comment by karlwilbur** [comment]
@amenthe,

I know it's likely a bit too late, but I wanted to offer up my thoughts. I suspect that you are using `my_email_attribute` in your model. Possible copy-pasted the example code form the `README`:

```ruby
validates :my_email_attribute, email: true
```

Though it doesn't explicitly state it, you are meant to replace `my_email_attribute` with the actual email property name used in your model; something like `email` or `email_address` or `user_email` or whatever it may be. Take a look and see if it might be something like what I have described. 

If you have already found a solution, please let us know what you found.
