### ISSUE TITLE
Badge points to other repo

### ISSUE THREAD

**Issue by olleolleolle** [K-and-R/email_validator#67]
- Travis build badge seems off.

**Comment by karlwilbur** [comment]
Yep. Travis wasn't updated the URL for the repo, so I merged your commit as-is ...then they updated the URL once there was a new commit to the `master` branch. I'll update it in my fork and it will get corrected then I merge that code.

Thanks for paying attention.

**Comment by karlwilbur** [comment]
This has been fixed.
