### ISSUE TITLE
2020.example.com is a valid fqdn

### ISSUE THREAD

**Issue by Spone** [K-and-R/email_validator#68]
Currently in `strict` mode:

```rb
EmailValidator.valid?("john.doe@2020.example.com", mode: :strict)
=> false
```

but `2020.example.com` is indeed a valid FQDN, right?

**Comment by karlwilbur** [comment]
Thanks, @Spone, good catch. I was operating on the [RFC-952 spec](https://tools.ietf.org/html/rfc952) which disallows hostnames beginning with non-alpha characters. This was definitely changed in the last 35 years (for example, [RFC-1123](https://tools.ietf.org/html/rfc1123)), and I should have caught that. I do know that hostnames can consist of only numbers, but primary domains cannot be only numeric. 

This example should be valid in all modes. I'll use your example above in the spec and get it fixed. I'll expect to have that done later today.

**Comment by karlwilbur** [comment]
Fixed in `v2.2.1`.

Thanks, @Spone, for reporting!

**Comment by Spone** [comment]
Thanks a lot, I managed to catch the issue by running the validation on a production database export, so thank you anonymous user who has a uncommon email :)

**Comment by delphaber** [comment]
I think primary domains can be only numeric. For example, the strict mode is marking emails like `john.doe@163.com` as invalid, but it turns out that `163.com` is a chinese service provider and so their email are valid 🤔  . I've created a PR to add a failing test: https://github.com/K-and-R/email_validator/pull/70

**Comment by xiaohui-zhangxh** [comment]
> I think primary domains can be only numeric. For example, the strict mode is marking emails like `john.doe@163.com` as invalid, but it turns out that `163.com` is a chinese service provider and so theirs email are valid 🤔 . I've created a PR to add a failing test: #70

This is true, `163.com`, `139.com` are most famous service provider in China, there are many emails are marked as invalid due to this issue.

**Comment by karlwilbur** [comment]
Yes! Thanks for catching this. @delphaber, can you please add this as a separate issue? Specifically something like "valid numeric domains are considered invalid strict mode."

I see the failing test in your PR. Thanks! Yeah, that will help make sure that we don't break it again, but I need to get in there and fix the validation RegEx. I hope to get to that in the next couple days.

**Comment by karlwilbur** [comment]
Specifically, for my own reference, [RFC 1123](https://tools.ietf.org/html/rfc1123) states:
> 2.1  Host Names and Numbers
>
>    The syntax of a legal Internet host name was specified in RFC-952
      [DNS:4].  One aspect of host name syntax is hereby changed: the
      restriction on the first character is relaxed to allow either a
      letter or a digit.  Host software MUST support this more liberal
      syntax.

**Comment by delphaber** [comment]
> valid numeric domains are considered invalid strict mode

will do!
